-- MySQL Script generated by MySQL Workbench
-- Wed Mar 30 12:01:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema evidencebusu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evidencebusu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `evidencebusu` DEFAULT CHARACTER SET utf8 ;
USE `evidencebusu` ;

-- -----------------------------------------------------
-- Table `evidencebusu`.`Spoj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidencebusu`.`Spoj` (
  `idSpoj` INT NOT NULL AUTO_INCREMENT,
  `cislospoje` INT NOT NULL,
  PRIMARY KEY (`idSpoj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evidencebusu`.`Cas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidencebusu`.`Cas` (
  `idCas` INT NOT NULL AUTO_INCREMENT,
  `prijezd` TIME NOT NULL,
  `odjezd` TIME NOT NULL,
  `mesto` VARCHAR(45) NOT NULL,
  `Spoj_idSpoj` INT NOT NULL,
  PRIMARY KEY (`idCas`, `Spoj_idSpoj`),
  INDEX `fk_Čas_Spoj_idx` (`Spoj_idSpoj` ASC) ,
  CONSTRAINT `fk_Čas_Spoj`
    FOREIGN KEY (`Spoj_idSpoj`)
    REFERENCES `evidencebusu`.`Spoj` (`idSpoj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
